name: deliverymoment-service
namespace: ""
cdPipelineName: ""
cdPipelineStageName: ""
dnsWildcard: 59ae6b648ca3437aae3a.westeurope.aksapp.io
framework: java11

database:
  required: false


ingress:
  required: true
  site: 
  path: /

image:
  name: deliverymoment-service
  version: latest